# Use Bun as base image
FROM oven/bun:1 AS base

# Install OpenSSL for Prisma
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy package files
COPY package.json bun.lockb* ./

# Copy Prisma schema for postinstall script
COPY prisma ./prisma

# Install dependencies (postinstall will run prisma generate)
RUN bun install --frozen-lockfile

# Copy application files
COPY . .

# Copy .env.production if it exists (for build-time environment variables)
# This allows NEXT_PUBLIC_* variables to be available during build
COPY .env.production* ./

# Prisma Client was already generated by postinstall script during bun install
# No need to regenerate unless schema changes after copying files

# Build Next.js
# IMPORTANT: NEXT_PUBLIC_* variables must be available at build time
# They are embedded into the JavaScript bundle and cannot be changed at runtime
ENV NEXT_TELEMETRY_DISABLED=1
ENV DOCKER_BUILD=true
ENV NODE_ENV=production
# Build args can be passed from docker-compose for build-time variables
ARG NEXT_PUBLIC_APP_URL
ARG NEXTAUTH_URL
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
RUN bun run build

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=production
ENV TZ=Asia/Bangkok

# Start the application
CMD ["bun", "run", "start"]

